version: "0.2"
phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 178502900821.dkr.ecr.ap-south-1.amazonaws.com
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - echo "Building docker image..."
      - docker build -t $ImageName -f simple-python-app/Dockerfile simple-python-app
      - docker images
  post_build:
    commands:
      - docker tag $ImageName:latest 178502900821.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest
      - docker push 178502900821.dkr.ecr.ap-south-1.amazonaws.com/$ImageName:latest
